### ISSUE TITLE
Latest update is not installable via Composer without using commit hash

### ISSUE THREAD

**Issue by greatislander** [gridonic/PrinceXMLPhp#9]
Hi! Thanks for merging in #8. It would much appreciated if you could tag a new release, because installing via Composer using your recommended method (`"gridonic/princexml-php": "*"`) still installs the latest tagged version ([1.1.1](https://github.com/gridonic/PrinceXMLPhp/releases/tag/1.1.1)) and not the latest commit which includes r15 of the wrapper. As a workaround, it can be installed by using:

`"gridonic/princexml-php": "dev-master#ebacd18a97dd5a6f8f75876e7a781d46d7b7d6fc"`

But it would be awesome if anyone who uses `composer require gridonic/princexml-php` would get the current wrapper. Thanks in advance!

**Comment by peschee** [comment]
Done.
